<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.r8Uh.Jg' shared service.

return $this->privates['.service_locator.r8Uh.Jg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true],
    'fileLogoCreate' => ['privates', 'App\\Services\\FileLogoCreate', 'getFileLogoCreateService.php', true],
    'foldersUser' => ['privates', 'App\\Services\\FoldersUser', 'getFoldersUserService.php', true],
    'securityManager' => ['privates', 'App\\Manager\\SecurityManager', 'getSecurityManagerService.php', true],
    'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService.php', true],
], [
    'em' => '?',
    'fileLogoCreate' => 'App\\Services\\FileLogoCreate',
    'foldersUser' => 'App\\Services\\FoldersUser',
    'securityManager' => 'App\\Manager\\SecurityManager',
    'userRepository' => 'App\\Repository\\UserRepository',
]);
