<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.4F7Ae6Z' shared service.

return $this->privates['.service_locator.4F7Ae6Z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'securityManager' => ['privates', 'App\\Manager\\SecurityManager', 'getSecurityManagerService.php', true],
    'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService.php', true],
], [
    'securityManager' => 'App\\Manager\\SecurityManager',
    'userRepository' => 'App\\Repository\\UserRepository',
]);
