<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.xz.z0Up' shared service.

return $this->privates['.service_locator.xz.z0Up'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'jobRepository' => ['privates', 'App\\Repository\\JobRepository', 'getJobRepositoryService.php', true],
], [
    'jobRepository' => 'App\\Repository\\JobRepository',
]);
