<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.uKjOS12' shared service.

return $this->privates['.service_locator.uKjOS12'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'rateRepository' => ['privates', 'App\\Repository\\RateRepository', 'getRateRepositoryService.php', true],
], [
    'rateRepository' => 'App\\Repository\\RateRepository',
]);
