<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.EYmbNWf' shared service.

return $this->privates['.service_locator.EYmbNWf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'adviceRepository' => ['privates', 'App\\Repository\\AdviceRepository', 'getAdviceRepositoryService.php', true],
    'rateRepository' => ['privates', 'App\\Repository\\RateRepository', 'getRateRepositoryService.php', true],
    'securityManager' => ['privates', 'App\\Manager\\SecurityManager', 'getSecurityManagerService.php', true],
    'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService.php', true],
], [
    'adviceRepository' => 'App\\Repository\\AdviceRepository',
    'rateRepository' => 'App\\Repository\\RateRepository',
    'securityManager' => 'App\\Manager\\SecurityManager',
    'userRepository' => 'App\\Repository\\UserRepository',
]);
