<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Manager\ApiSireneManager' shared autowired service.

include_once $this->targetDirs[3].'/src/Manager/ApiSireneManager.php';
include_once $this->targetDirs[3].'/src/Manager/ApiCompanyManager.php';
include_once $this->targetDirs[3].'/src/Manager/ApiNomenclaturesManager.php';
include_once $this->targetDirs[3].'/src/Manager/ApiCategorieTable.php';

$a = ($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php'));

return $this->privates['App\\Manager\\ApiSireneManager'] = new \App\Manager\ApiSireneManager($a, ($this->privates['App\\Repository\\UserRepository'] ?? $this->load('getUserRepositoryService.php')), new \App\Manager\ApiCompanyManager($a), new \App\Manager\ApiNomenclaturesManager($a, ($this->privates['App\\Repository\\JobRepository'] ?? $this->load('getJobRepositoryService.php')), new \App\Manager\ApiCategorieTable(), ($this->privates['App\\Repository\\CategoryRepository'] ?? $this->load('getCategoryRepositoryService.php'))));
