<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Command\DbCommand' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/src/Command/DbCommand.php';
include_once $this->targetDirs[3].'/src/Manager/ManualFixtureManagerV2.php';

$this->privates['App\\Command\\DbCommand'] = $instance = new \App\Command\DbCommand(new \App\Manager\ManualFixtureManagerV2(($this->privates['App\\Repository\\UserRepository'] ?? $this->load('getUserRepositoryService.php')), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')), ($this->privates['App\\Manager\\ApiSireneManager'] ?? $this->load('getApiSireneManagerService.php')), ($this->services['security.password_encoder'] ?? $this->load('getSecurity_PasswordEncoderService.php'))));

$instance->setName('app:db');

return $instance;
