<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Services\FoldersUser' shared autowired service.

include_once $this->targetDirs[3].'/src/Services/FoldersUser.php';

return $this->privates['App\\Services\\FoldersUser'] = new \App\Services\FoldersUser();
