<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Services\FileTablePictures' shared autowired service.

include_once $this->targetDirs[3].'/src/Services/FileTablePictures.php';

return $this->privates['App\\Services\\FileTablePictures'] = new \App\Services\FileTablePictures();
