<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Services\FileLogoCreate' shared autowired service.

include_once $this->targetDirs[3].'/src/Services/FileLogoCreate.php';

return $this->privates['App\\Services\\FileLogoCreate'] = new \App\Services\FileLogoCreate();
