<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Manager\SecurityManager' shared autowired service.

include_once $this->targetDirs[3].'/src/Manager/SecurityManager.php';

return $this->privates['App\\Manager\\SecurityManager'] = new \App\Manager\SecurityManager();
