<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\SecurityController' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
include_once $this->targetDirs[3].'/src/Controller/SecurityController.php';
include_once $this->targetDirs[3].'/src/Manager/SecurityManager.php';

$this->services['App\\Controller\\SecurityController'] = $instance = new \App\Controller\SecurityController(($this->services['App\\Controller\\ExterneApiController'] ?? $this->load('getExterneApiControllerService.php')), ($this->privates['App\\Manager\\SecurityManager'] ?? ($this->privates['App\\Manager\\SecurityManager'] = new \App\Manager\SecurityManager())), ($this->services['App\\Controller\\MailController'] ?? $this->load('getMailControllerService.php')));

$instance->setContainer(($this->privates['.service_locator.CDOTD6.'] ?? $this->load('get_ServiceLocator_CDOTD6_Service.php'))->withContext('App\\Controller\\SecurityController', $this));

return $instance;
