<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV14doVB\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV14doVB/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerV14doVB.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerV14doVB\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerV14doVB\srcApp_KernelProdContainer([
    'container.build_hash' => 'V14doVB',
    'container.build_id' => '0ef612f3',
    'container.build_time' => 1589471470,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV14doVB');
