<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'api_advice__add' => [[], ['_controller' => 'App\\Controller\\ApiAdviceController::add'], [], [['text', '/api/v1/advice/add']], [], []],
    'api_advice__report' => [[], ['_controller' => 'App\\Controller\\ApiAdviceController::report'], [], [['text', '/api/v1/advice/report']], [], []],
    'api_artisan_edit' => [[], ['_controller' => 'App\\Controller\\ApiArtisanController::edit'], [], [['text', '/api/v1/artisan/edit']], [], []],
    'artisan_all' => [[], ['_controller' => 'App\\Controller\\ApiArtisanController::all'], [], [['text', '/v1/artisan/list']], [], []],
    'artisan_recherche' => [[], ['_controller' => 'App\\Controller\\ApiArtisanController::searchByRate'], [], [['text', '/v1/artisan/recherche']], [], []],
    'artisan_single' => [[], ['_controller' => 'App\\Controller\\ApiArtisanController::single'], [], [['text', '/v1/artisan/single']], [], []],
    'api_job_category' => [[], ['_controller' => 'App\\Controller\\ApiJobController::categoryList'], [], [['text', '/v1/job/category/list']], [], []],
    'api_job_categoryV2' => [[], ['_controller' => 'App\\Controller\\ApiJobController::categoryListV2'], [], [['text', '/v1/job/category/listV2']], [], []],
    'api_job_job' => [[], ['_controller' => 'App\\Controller\\ApiJobController::jobListFromCategory'], [], [['text', '/v1/job/list']], [], []],
    'api_rate_add' => [[], ['_controller' => 'App\\Controller\\ApiRateController::add'], [], [['text', '/api/v1/rate/add']], [], []],
    'api_rate_single' => [[], ['_controller' => 'App\\Controller\\ApiRateController::single'], [], [['text', '/api/v1/rate/single']], [], []],
    'api_region_list' => [[], ['_controller' => 'App\\Controller\\ApiRegionController::getRegionList'], [], [['text', '/v1/region/list']], [], []],
    'api_user_edit' => [[], ['_controller' => 'App\\Controller\\ApiUserController::edit'], [], [['text', '/api/v1/user/edit']], [], []],
    'api_user_delete' => [[], ['_controller' => 'App\\Controller\\ApiUserController::delete'], [], [['text', '/api/v1/user/delete']], [], []],
    'api_user_all' => [[], ['_controller' => 'App\\Controller\\ApiUserController::all'], [], [['text', '/api/v1/user/list']], [], []],
    'api_user_single' => [[], ['_controller' => 'App\\Controller\\ApiUserController::single'], [], [['text', '/api/v1/user/single']], [], []],
    'sirene' => [['id'], ['_controller' => 'App\\Controller\\ExterneApiController::ApiTestSirene'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/sirene/test']], [], []],
    'api_mail_check' => [[], ['_controller' => 'App\\Controller\\MailController::mailCheck'], [], [['text', '/api/v1/checkMail']], [], []],
    'mail_confirm' => [[], ['_controller' => 'App\\Controller\\MailController::sendMailValidation'], [], [['text', '/confirmMail']], [], []],
    'api_reset_pass' => [[], ['_controller' => 'App\\Controller\\MailController::sendResetPass'], [], [['text', '/resetPassMail']], [], []],
    'api_confirm_route' => [[], ['_controller' => 'App\\Controller\\MailController::comfirmRoute'], [], [['text', '/confirmation']], [], []],
    'main' => [[], ['_controller' => 'App\\Controller\\MainController::index'], [], [['text', '/']], [], []],
    'app_register_artisan' => [[], ['_controller' => 'App\\Controller\\SecurityController::registerArtisan'], [], [['text', '/register/artisan']], [], []],
    'app_register_user' => [[], ['_controller' => 'App\\Controller\\SecurityController::registerUser'], [], [['text', '/register/user']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'easyadmin' => [[], ['_controller' => 'EasyCorp\\Bundle\\EasyAdminBundle\\Controller\\EasyAdminController::indexAction'], [], [['text', '/admin/']], [], []],
    'api_login_check' => [[], [], [], [['text', '/api/login_check']], [], []],
];
